# Generated by Django 3.2.8 on 2021-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_role_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Programmer', 'Programmer'), ('Team Leader', 'Team Leader')], default='Programmer', max_length=100, null=None),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
