# Generated by Django 3.2.8 on 2021-10-27 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='worker_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
