# Generated by Django 3.2.8 on 2021-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In proccess', 'In proccess'), ('Done', 'Done'), ('Closed', 'Closed')], default='Created', max_length=100, null=None),
        ),
    ]
