# Generated by Django 3.2.8 on 2021-10-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
