# Generated by Django 3.2.8 on 2021-10-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Programmer', 'Programmer'), ('Team Leader', 'Team Leader')], default='Programmer', max_length=25, null=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In proccess', 'In proccess'), ('Done', 'Done'), ('Closed', 'Closed')], default='Created', max_length=25, null=None),
        ),
    ]
