# Generated by Django 3.2.8 on 2022-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In process', 'In process'), ('Done', 'Done'), ('Closed', 'Closed')], default='Created', max_length=25, null=True),
        ),
    ]
